---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-stuff

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-configmap
  namespace: nginx-stuff
data:
  hello: "world"

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: nginx-stuff
spec:
  containers:
  - image: bitnami/nginx:1.20
    name: nginx
    command:
      - /opt/bitnami/scripts/nginx/entrypoint.sh
      - /opt/bitnami/scripts/nginx/run.sh
    livenessProbe:
      tcpSocket:
        port: 8080
    readinessProbe:
      tcpSocket:
        port: 8080
    resources: {}
    ports:
      - containerPort: 8080
      - containerPort: 8443
  volumes:
  - name: demo-volume
    configMap:
      name: demo-configmap
  dnsPolicy: Default
