---
apiVersion: v1
kind: Pod
metadata:
  name: zombie
spec:
  containers:
  - image: bitnami/nginx:1.20
    name: zombie
    command: ["/bin/bash","-c", "set -e && /opt/bitnami/scripts/nginx/run.sh & exec sleep infinity"]
    livenessProbe:
      tcpSocket:
        port: 8080
    readinessProbe:
      tcpSocket:
        port: 8080
    resources: {}
  dnsPolicy: Default
