apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  volumes:
  - name: root-tmp
    emptyDir: {}
  - name: bitnami-tmp
    emptyDir: {}

  containers:
  - image: bitnami/nginx:1.20
    name: nginx
    command:
      - /opt/bitnami/scripts/nginx/entrypoint.sh
      - /opt/bitnami/scripts/nginx/run.sh
    securityContext:
      readOnlyRootFilesystem: true
    livenessProbe:
      tcpSocket:
        port: 8080
    readinessProbe:
      tcpSocket:
        port: 8080
    resources: {}
    ports:
      - containerPort: 8080
      - containerPort: 8443
    volumeMounts:
    - name: root-tmp
      mountPath: /tmp
    - name: bitnami-tmp
      mountPath: /opt/bitnami/nginx/tmp
  dnsPolicy: Default
