---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-tini-sample
spec:
  dnsPolicy: Default

  containers:
  - image: hashnuke/cnf-testsuite-specialized-init-sample:0.2
    name: nginx
    command: ["/tini", "--"]
    args: ["nginx", "-g", "daemon off;"]
    securityContext:
      allowPrivilegeEscalation: false
    livenessProbe:
      tcpSocket:
        port: 80
    readinessProbe:
      tcpSocket:
        port: 80
    resources: {}
    ports:
      - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-dumb-init-sample
spec:
  dnsPolicy: Default

  containers:
  - image: hashnuke/cnf-testsuite-specialized-init-sample:0.2
    name: nginx-dumb-init
    command: ["/usr/bin/dumb-init", "--"]
    args: ["nginx", "-g", "daemon off;"]
    securityContext:
      allowPrivilegeEscalation: false
    livenessProbe:
      tcpSocket:
        port: 80
    readinessProbe:
      tcpSocket:
        port: 80
    resources: {}
    ports:
      - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-s6-overlay-sample
spec:
  dnsPolicy: Default

  containers:
  - image: hashnuke/cnf-testsuite-specialized-init-sample:0.2
    name: nginx-dumb-init
    command: ["/init"]
    args: ["nginx", "-g", "daemon off;"]
    securityContext:
      allowPrivilegeEscalation: false
    livenessProbe:
      tcpSocket:
        port: 80
    readinessProbe:
      tcpSocket:
        port: 80
    resources: {}
    ports:
      - containerPort: 80
