apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "envoy.fullname" . }}-xds
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "envoy.name" . }}
    chart: {{ template "envoy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- range $filename, $content := .Values.xds }}
  {{ tpl $filename $ }}: |-
{{ $valueWithDefault := default "" $content -}}
{{ tpl $valueWithDefault $ | indent 4 }}
{{- end -}}
