{{ $open5gsName := .Release.Name }}
logger:
  level: {{ .Values.config.logLevel }}
parameter: {}

sbi:
  server:
    no_tls: {{ .Values.config.sbi.server.no_tls }}
  client:
    no_tls: {{ .Values.config.sbi.client.no_tls }}

udm:
  hnet:
    - id: 1
      scheme: 1
      key: /etc/open5gs/hnet/curve25519-1.key
    - id: 2
      scheme: 2
      key: /etc/open5gs/hnet/secp256r1-2.key

udm:
  sbi:
    - dev: "eth0"
      port: {{ .Values.containerPorts.sbi }}
      {{- if .Values.config.sbi.advertise }}
      advertise: "{{ tpl .Values.config.sbi.advertise . }}"
      {{- end }}

nrf:
  sbi:
    - name: {{ default (printf "%s-nrf-sbi" $open5gsName) .Values.config.nrf.sbi.hostname }}
      port: {{ .Values.config.nrf.sbi.port }}
